export enum StatusEnum {
    PENDIENTE_SOLICITUD = 'PENDIENTE_SOLICITUD',
    ASIGNADO_ANALISTA = 'ASIGNADO_ANALISTA',
    PENDIENTE_APROBACION = 'PENDIENTE_APROBACION',
    APROBADO = 'APROBADO',
    EN_PROGRESO = 'EN_PROGRESO',
    COMPLETADO = 'COMPLETADO',
    RECHAZADO = 'RECHAZADO'
}